imageList = [
  ('images/test1.jpeg', 'test1', 'jpg'),
  ('images/test2.jpeg', 'test2', 'jpg'),
  ('images/test3.jpg', 'test3', 'jpg'),
  ('images/test4.jpg', 'test4', 'jpg'),
  ('images/test5.jpg', 'test5', 'jpg'),
  ('images/test6.jpg', 'test6', 'jpg'),
  ('images/test7.jpg', 'test7', 'jpg'),
  ('images/test8.jpg', 'test8', 'jpg'),
  ('images/test9.jpg', 'test9', 'jpg'),
  ('images/test10.jpg', 'test10', 'jpg'),
  ('images/test11.jpg', 'test11', 'jpg'),
  ('images/test12.png', 'test12', 'png'),
  ('images/test13.png', 'test13', 'png'),
  ('images/test14.jpg', 'test14', 'jpg'),
  ('images/test15.png', 'test15', 'png'),
  ('images/m1.jpg', 'm1', 'jpg'),
  ('images/m2.jpg', 'm2', 'jpg')
]